name: Build QMK Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
          - planck.json

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout Userspace
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}

      - name: Build Firmware
        run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ github.actor }}_${{ github.sha }}_${{ matrix.file }}
          path: |
            *.hex
            *.bin
            *.uf2
